### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/scran#3]
- [x] Need to add support for ranked `overlapExprs` output.
- [x] Need to modify `trendVar` and `decomposeVar` to report zero residual d.f. for all-zero groups.
- [x] Need to modify `findMarkers` to correctly compute variance in the presence of all-zero groups.
- [x] Need to modify `findMarkers` to test residuals with `design=`, rather than fitting a linear model.
- [x] Need to switch `findMarkers` to doing pairwise Welch t-tests.
- [x] Need to modify residual calculations to add back coefficients, like `removeBatchEffect`.
